site: Anateo - formations par visio seul ou en groupe

url: 
baseurl: /made

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /blog/:slug
  projects:
    output: true
    permalink: /project/:slug
  copie:
    output: true
    permalink: /copie/:slug
  formation-rgpd:
    output: true
    permalink: /formation-rgpd/:slug
  formation-sapin2:
    output: true
    permalink: /formation-sapin2/:slug

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "projects"
    values:
      layout: "project"
  -
    scope:
      path: ""
      type: "copie"
    values:
      layout: "project"
  -
    scope:
      path: ""
      type: "formation-rgpd"
    values:
      layout: "project"
  -
    scope:
      path: ""
      type: "formation-sapin2"
    values:
      layout: "project"

markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1
  
sass:
  style: compressed

plugins:
  - jekyll-sitemap

paginate: 7
paginate_path: "/blog/page-:num/"